### ISSUE TITLE
The rationale to make I/O APIs isolated

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/module-ballerina-io#7]
### Print APIs
All print-related APIs can constraint as isolated since those APIs don't access any external variables other than the arguments that pass. Even in the Java native APIs follow the same. The print-related APIs should mark as isolated, otherwise, print functionality cannot be accessible within any other isolated functions.

### Stdin Read APIs
The `readln` API shouldn't be an isolated one since it returns a dynamic value. I don't see any adding value when it makes isolated.

### File Read and Write Operations
IMO, this file read and write operations shouldn't be isolated. It seems isolated in ballerina context. But when it comes to UNIX implementations those are not thread-safe. Thus, making those APIs, thread-safe would be semantically incorrect. This is similarly applicable for file init and close operations too.

Further, there can be shared file read/write use cases where we thread safety is unnecessary.

[1] https://docs.oracle.com/cd/E19455-01/806-5257/6je9h033b/index.html

### Affected Product Version
SLP4

**Comment by BuddhiWathsala** [comment]
@MaryamZi @daneshk @shafreenAnfar WDYT?

**Comment by chamil321** [comment]
I think we have to consider basically two conditions here. 
1. Semantically whether this function should be isolated or not.
2. How frequently these functions have been used by other dependent modules and Would those dependent module functions get disturbed by not isolating IO APIs.

The considerations mentioned above have focused on the first condition. But to fulfill the second condition, public APIs need to be isolated IMO. Otherwise, those dependent modules cannot use these APIs from their isolated functions.

**Comment by BuddhiWathsala** [comment]
IMO, we have to make these IO read/write non-isolated because these read/write may access shared resources and therefore we cannot guarantee 100% isolation. Then the higher-level APIs that access this IO read/write operations shouldn't be isolated. 

Isn't that the case?. To make higher-level APIs isolated, forcefully converting non-isolated lower-level APIs to isolated will be an incorrect design decision.

**Comment by chamil321** [comment]
I think we have this same issue with the Config-API module as well IINM. Eventually, the team decided to make those APIs isolated by making implementation thread-safe. For example, If you access a shared resource, that needs to be done within a lock. So can't we apply the same approach here as well?
